id: IE77BFA2E
legacy_id: P009364
ocr_import_info:
  bdrc_scan_id: W10237
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T04:08:11'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:53:04.926221+00:00'
last_modified: 2022-08-29 20:53:18.701401
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W10237
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW10237
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀྱེ་རྡོ་རྗེའི་མངོན་པར་རྟོགས་པ་འབྲིང་དུ་བྱ་བ།
  author: ངོར་མཁན་ཆེན ༡༠་དཀོན་མཆོག་ལྷུན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.5993675056423632
  ocr_word_median_confidence_index: 0.6299999952316284
quality: null
bases:
  I1561:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1561
      total_pages: 140
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1561.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.5993675056423632
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
